from pathlib import Path

from pptx import Presentation

from app.agents.deck_planner_agent import DeckPlannerAgent
from app.agents.grounding_checker import GroundingChecker
from app.agents.paper_summary_agent import PaperSummaryAgent
from app.agents.quality_checker import SlideQualityChecker
from app.agents.slide_writer_agent import SlideWriterAgent
from app.llm.providers import MockLLMProvider
from app.parser.pdf_parser import PDFParser
from app.schemas.common import GenerationSettings
from app.utils.text_utils import contains_ellipsis, count_cjk


def load_sample_paper():
    fixture = Path(__file__).parent / "fixtures" / "sample_paper.pdf"
    return PDFParser().parse(fixture, paper_id="paper_quality")


def test_summary_uses_chinese_grounded_output():
    paper = load_sample_paper()
    summary = PaperSummaryAgent(MockLLMProvider(paper)).run(paper)
    assert "uncertain" not in summary.problem.lower()
    assert "uncertain" not in summary.method_overview.lower()
    assert "待补充" not in summary.conclusion
    assert count_cjk(summary.problem + summary.method_overview + summary.conclusion) > 10


def test_slide_writer_outputs_chinese_report_quality():
    paper = load_sample_paper()
    llm = MockLLMProvider(paper)
    summary = PaperSummaryAgent(llm).run(paper)
    plan = DeckPlannerAgent(llm).run(paper, summary, GenerationSettings(slide_count=12))
    drafts = SlideWriterAgent(llm).run(paper, summary, plan)

    for slide in drafts.slides:
        assert "Confidence" not in slide.title
        assert "Confidence" not in slide.key_message
        assert "uncertain" not in slide.key_message.lower()
        assert not contains_ellipsis(slide.title)
        assert not contains_ellipsis(slide.key_message)
        if slide.slide_type not in {"title", "divider"}:
            assert count_cjk(slide.title) <= 14
            assert 2 <= len(slide.bullets) <= 4
            for bullet in slide.bullets:
                assert not contains_ellipsis(bullet)
                assert "uncertain" not in bullet.lower()
                assert "Confidence" not in bullet

    method_slide = next(slide for slide in drafts.slides if slide.slide_type == "method")
    result_slide = next(slide for slide in drafts.slides if slide.slide_type == "results")
    assert any(ref.section_title == "Method" for ref in method_slide.source_refs)
    assert any(ref.section_title == "Results" for ref in result_slide.source_refs)


def test_quality_checker_flags_low_quality_content():
    report = SlideQualityChecker().run(
        SlideWriterAgent(MockLLMProvider(load_sample_paper())).run(
            load_sample_paper(),
            PaperSummaryAgent(MockLLMProvider(load_sample_paper())).run(load_sample_paper()),
            DeckPlannerAgent(MockLLMProvider(load_sample_paper())).run(
                load_sample_paper(),
                PaperSummaryAgent(MockLLMProvider(load_sample_paper())).run(load_sample_paper()),
                GenerationSettings(slide_count=8),
            ),
        )
    )
    assert report.passed


def test_grounding_checker_runs_on_quality_drafts():
    paper = load_sample_paper()
    llm = MockLLMProvider(paper)
    summary = PaperSummaryAgent(llm).run(paper)
    plan = DeckPlannerAgent(llm).run(paper, summary, GenerationSettings(slide_count=10))
    drafts = SlideWriterAgent(llm).run(paper, summary, plan)
    report = GroundingChecker().run(drafts)
    assert report.slide_count == len(drafts.slides)


def test_title_slide_is_not_text_dump(tmp_path: Path):
    paper = load_sample_paper()
    llm = MockLLMProvider(paper)
    summary = PaperSummaryAgent(llm).run(paper)
    plan = DeckPlannerAgent(llm).run(paper, summary, GenerationSettings(slide_count=10, language="zh"))
    drafts = SlideWriterAgent(llm).run(paper, summary, plan)

    from app.ppt.ppt_builder import PPTBuilder

    output = tmp_path / "deck.pptx"
    PPTBuilder().build(output, summary, plan, drafts, GenerationSettings(language="zh"))
    prs = Presentation(output)
    title_texts = [shape.text for shape in prs.slides[0].shapes if hasattr(shape, "text") and shape.text.strip()]
    assert "Confidence" not in "\n".join(title_texts)
    assert "Generated by Personalized Paper-to-PPT Agent" not in "\n".join(title_texts)
    assert count_cjk(title_texts[0]) > 0
