from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from app.ppt.themes import get_theme
from app.schemas.common import GenerationSettings
from app.schemas.deck import DeckPlan, PaperSummary, SlideDraft, SlideDrafts


class PPTBuilder:
    def build(
        self,
        output_path: Path,
        summary: PaperSummary,
        plan: DeckPlan,
        drafts: SlideDrafts,
        settings: GenerationSettings,
    ) -> Path:
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)
        theme = get_theme(settings.theme)

        slide_type_map = {item.slide_id: item.slide_type for item in plan.slides}
        for index, draft in enumerate(drafts.slides):
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            slide_type = slide_type_map.get(draft.slide_id, "content")
            self._render_slide(slide, slide_type, draft, summary, theme, settings)
            if settings.include_speaker_notes and draft.speaker_notes:
                self._attach_notes(slide, draft.speaker_notes)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        prs.save(output_path)
        return output_path

    def _set_background(self, slide, rgb: tuple[int, int, int]) -> None:
        fill = slide.background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(*rgb)

    def _render_slide(self, slide, slide_type: str, draft: SlideDraft, summary: PaperSummary, theme, settings: GenerationSettings) -> None:
        if slide_type == "title":
            self._set_background(slide, (245, 247, 250))
            self._render_title_slide(slide, draft.title, draft.subtitle, draft.key_message, theme)
        elif slide_type == "divider":
            self._set_background(slide, (231, 238, 255))
            self._render_divider_slide(slide, draft.title, draft.subtitle or draft.key_message, theme)
        elif slide_type in {"method", "technical"}:
            self._set_background(slide, theme.background_color)
            self._render_two_panel_slide(slide, draft, theme, settings, accent=(37, 99, 235))
        elif slide_type in {"results", "analysis"}:
            self._set_background(slide, (248, 250, 252))
            self._render_result_slide(slide, draft, theme, settings)
        elif slide_type == "limitations":
            self._set_background(slide, (255, 247, 237))
            self._render_limitation_slide(slide, draft, theme, settings)
        elif slide_type == "discussion":
            self._set_background(slide, (240, 253, 250))
            self._render_discussion_slide(slide, draft, theme, settings)
        elif slide_type == "conclusion":
            self._set_background(slide, (239, 246, 255))
            self._render_conclusion_slide(slide, draft, summary, theme, settings)
        else:
            self._set_background(slide, theme.background_color)
            self._render_content_slide(slide, draft, theme, settings)

    def _render_title_slide(self, slide, title: str, subtitle: str, key_message: str, theme) -> None:
        banner = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(1.1))
        banner.fill.solid()
        banner.fill.fore_color.rgb = RGBColor(30, 64, 175)
        banner.line.fill.background()

        title_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.2), Inches(11.6), Inches(1.8))
        title_frame = title_box.text_frame
        p = title_frame.paragraphs[0]
        p.text = title
        p.font.size = Pt(theme.title_font_size + 8)
        p.font.bold = True
        p.font.color.rgb = RGBColor(*theme.title_color)
        p.alignment = PP_ALIGN.LEFT

        subtitle_box = slide.shapes.add_textbox(Inches(0.8), Inches(3.2), Inches(8.6), Inches(1.0))
        subtitle_frame = subtitle_box.text_frame
        sp = subtitle_frame.paragraphs[0]
        sp.text = subtitle or "Generated by Personalized Paper-to-PPT Agent"
        sp.font.size = Pt(theme.body_font_size)
        sp.font.color.rgb = RGBColor(*theme.accent_color)

        takeaway_box = slide.shapes.add_textbox(Inches(0.8), Inches(4.55), Inches(10.8), Inches(1.25))
        takeaway_tf = takeaway_box.text_frame
        tp = takeaway_tf.paragraphs[0]
        tp.text = key_message
        tp.font.size = Pt(theme.body_font_size + 2)
        tp.font.bold = True
        tp.font.color.rgb = RGBColor(51, 65, 85)

    def _render_divider_slide(self, slide, title: str, subtitle: str, theme) -> None:
        stripe = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.RECTANGLE, Inches(0.7), Inches(0.8), Inches(0.24), Inches(5.8))
        stripe.fill.solid()
        stripe.fill.fore_color.rgb = RGBColor(37, 99, 235)
        stripe.line.fill.background()

        title_box = slide.shapes.add_textbox(Inches(1.3), Inches(2.0), Inches(10.4), Inches(1.2))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(theme.title_font_size + 10)
        p.font.bold = True
        p.font.color.rgb = RGBColor(15, 23, 42)

        subtitle_box = slide.shapes.add_textbox(Inches(1.35), Inches(3.4), Inches(8.8), Inches(1.2))
        sf = subtitle_box.text_frame
        sp = sf.paragraphs[0]
        sp.text = subtitle
        sp.font.size = Pt(theme.body_font_size + 1)
        sp.font.color.rgb = RGBColor(71, 85, 105)

    def _render_content_slide(self, slide, draft: SlideDraft, theme, settings: GenerationSettings) -> None:
        title_box = slide.shapes.add_textbox(Inches(0.7), Inches(0.4), Inches(12), Inches(0.8))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = draft.title
        p.font.size = Pt(theme.title_font_size)
        p.font.bold = True
        p.font.color.rgb = RGBColor(*theme.title_color)

        key_box = slide.shapes.add_textbox(Inches(0.9), Inches(1.3), Inches(11.3), Inches(0.7))
        key_tf = key_box.text_frame
        kp = key_tf.paragraphs[0]
        kp.text = draft.key_message
        kp.font.size = Pt(theme.body_font_size - 1)
        kp.font.bold = True
        kp.font.color.rgb = RGBColor(37, 99, 235)

        body_box = slide.shapes.add_textbox(Inches(0.9), Inches(2.0), Inches(10.9), Inches(4.2))
        body_tf = body_box.text_frame
        body_tf.word_wrap = True
        for idx, bullet in enumerate(draft.bullets[:5]):
            paragraph = body_tf.paragraphs[0] if idx == 0 else body_tf.add_paragraph()
            paragraph.text = bullet
            paragraph.level = 0
            paragraph.font.size = Pt(theme.body_font_size)
            paragraph.font.color.rgb = RGBColor(*theme.body_color)
            paragraph.space_after = Pt(8)

        self._render_meta(slide, draft, theme, settings)

    def _render_two_panel_slide(self, slide, draft: SlideDraft, theme, settings: GenerationSettings, accent: tuple[int, int, int]) -> None:
        self._render_header(slide, draft.title, draft.key_message, theme, accent)
        left = slide.shapes.add_textbox(Inches(0.8), Inches(1.9), Inches(6.0), Inches(3.9))
        ltf = left.text_frame
        ltf.word_wrap = True
        for idx, bullet in enumerate(draft.bullets[:3]):
            para = ltf.paragraphs[0] if idx == 0 else ltf.add_paragraph()
            para.text = bullet
            para.font.size = Pt(theme.body_font_size)
            para.font.color.rgb = RGBColor(*theme.body_color)
            para.space_after = Pt(10)

        panel = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, Inches(7.2), Inches(1.9), Inches(5.2), Inches(3.9))
        panel.fill.solid()
        panel.fill.fore_color.rgb = RGBColor(239, 246, 255)
        panel.line.color.rgb = RGBColor(*accent)
        note_box = slide.shapes.add_textbox(Inches(7.45), Inches(2.2), Inches(4.7), Inches(3.2))
        ntf = note_box.text_frame
        np = ntf.paragraphs[0]
        np.text = "\n".join(draft.bullets[3:5] or ["Explain the structure, data flow, and design tradeoffs here."])
        np.font.size = Pt(theme.body_font_size - 1)
        np.font.color.rgb = RGBColor(30, 41, 59)
        self._render_meta(slide, draft, theme, settings)

    def _render_result_slide(self, slide, draft: SlideDraft, theme, settings: GenerationSettings) -> None:
        self._render_header(slide, draft.title, draft.key_message, theme, (5, 150, 105))
        highlight = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, Inches(0.85), Inches(1.7), Inches(3.2), Inches(1.2))
        highlight.fill.solid()
        highlight.fill.fore_color.rgb = RGBColor(220, 252, 231)
        highlight.line.fill.background()
        htf = highlight.text_frame
        hp = htf.paragraphs[0]
        hp.text = draft.bullets[0] if draft.bullets else draft.key_message
        hp.font.size = Pt(theme.body_font_size - 1)
        hp.font.bold = True
        hp.font.color.rgb = RGBColor(22, 101, 52)

        body_box = slide.shapes.add_textbox(Inches(4.4), Inches(1.7), Inches(7.5), Inches(4.5))
        btf = body_box.text_frame
        btf.word_wrap = True
        for idx, bullet in enumerate(draft.bullets[1:5] or draft.bullets[:4]):
            para = btf.paragraphs[0] if idx == 0 else btf.add_paragraph()
            para.text = bullet
            para.font.size = Pt(theme.body_font_size)
            para.font.color.rgb = RGBColor(*theme.body_color)
            para.space_after = Pt(10)
        self._render_meta(slide, draft, theme, settings)

    def _render_limitation_slide(self, slide, draft: SlideDraft, theme, settings: GenerationSettings) -> None:
        self._render_header(slide, draft.title, draft.key_message, theme, (234, 88, 12))
        warning_box = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, Inches(0.85), Inches(1.75), Inches(11.3), Inches(3.9))
        warning_box.fill.solid()
        warning_box.fill.fore_color.rgb = RGBColor(255, 237, 213)
        warning_box.line.color.rgb = RGBColor(234, 88, 12)
        tf = slide.shapes.add_textbox(Inches(1.1), Inches(2.0), Inches(10.8), Inches(3.2)).text_frame
        for idx, bullet in enumerate(draft.bullets[:5]):
            para = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
            para.text = bullet
            para.font.size = Pt(theme.body_font_size)
            para.font.color.rgb = RGBColor(124, 45, 18)
            para.space_after = Pt(10)
        self._render_meta(slide, draft, theme, settings)

    def _render_discussion_slide(self, slide, draft: SlideDraft, theme, settings: GenerationSettings) -> None:
        self._render_header(slide, draft.title, draft.key_message, theme, (13, 148, 136))
        for idx, bullet in enumerate(draft.bullets[:4]):
            y = 1.75 + idx * 1.1
            bubble = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, Inches(0.95), Inches(y), Inches(11.0), Inches(0.78))
            bubble.fill.solid()
            bubble.fill.fore_color.rgb = RGBColor(204, 251, 241)
            bubble.line.fill.background()
            tf = slide.shapes.add_textbox(Inches(1.2), Inches(y + 0.08), Inches(10.4), Inches(0.55)).text_frame
            para = tf.paragraphs[0]
            para.text = bullet
            para.font.size = Pt(theme.body_font_size - 1)
            para.font.color.rgb = RGBColor(17, 94, 89)
        self._render_meta(slide, draft, theme, settings)

    def _render_conclusion_slide(self, slide, draft: SlideDraft, summary: PaperSummary, theme, settings: GenerationSettings) -> None:
        self._render_header(slide, draft.title, draft.key_message, theme, (37, 99, 235))
        summary_box = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE, Inches(0.95), Inches(1.85), Inches(11.1), Inches(2.2))
        summary_box.fill.solid()
        summary_box.fill.fore_color.rgb = RGBColor(219, 234, 254)
        summary_box.line.fill.background()
        tf = slide.shapes.add_textbox(Inches(1.2), Inches(2.15), Inches(10.5), Inches(1.5)).text_frame
        para = tf.paragraphs[0]
        para.text = summary.conclusion
        para.font.size = Pt(theme.body_font_size + 1)
        para.font.bold = True
        para.font.color.rgb = RGBColor(30, 64, 175)

        body = slide.shapes.add_textbox(Inches(1.1), Inches(4.45), Inches(10.8), Inches(1.5)).text_frame
        for idx, bullet in enumerate(draft.bullets[:3]):
            bp = body.paragraphs[0] if idx == 0 else body.add_paragraph()
            bp.text = bullet
            bp.font.size = Pt(theme.body_font_size - 1)
            bp.font.color.rgb = RGBColor(*theme.body_color)
            bp.space_after = Pt(8)
        self._render_meta(slide, draft, theme, settings)

    def _render_header(self, slide, title: str, key_message: str, theme, accent: tuple[int, int, int]) -> None:
        line = slide.shapes.add_shape(MSO_AUTO_SHAPE_TYPE.RECTANGLE, Inches(0.75), Inches(0.55), Inches(0.18), Inches(0.9))
        line.fill.solid()
        line.fill.fore_color.rgb = RGBColor(*accent)
        line.line.fill.background()
        title_box = slide.shapes.add_textbox(Inches(1.05), Inches(0.42), Inches(11.1), Inches(0.7))
        tf = title_box.text_frame
        p = tf.paragraphs[0]
        p.text = title
        p.font.size = Pt(theme.title_font_size)
        p.font.bold = True
        p.font.color.rgb = RGBColor(*theme.title_color)
        key_box = slide.shapes.add_textbox(Inches(1.08), Inches(1.08), Inches(10.9), Inches(0.55))
        ktf = key_box.text_frame
        kp = ktf.paragraphs[0]
        kp.text = key_message
        kp.font.size = Pt(theme.body_font_size - 1)
        kp.font.color.rgb = RGBColor(*accent)
        kp.font.bold = True

    def _render_meta(self, slide, draft: SlideDraft, theme, settings: GenerationSettings) -> None:
        confidence_box = slide.shapes.add_textbox(Inches(11.1), Inches(0.45), Inches(1.4), Inches(0.35))
        ctf = confidence_box.text_frame
        cp = ctf.paragraphs[0]
        cp.text = f"Confidence: {draft.confidence}"
        cp.font.size = Pt(theme.footer_font_size)
        cp.font.color.rgb = RGBColor(100, 116, 139)
        if settings.include_source_footers and draft.source_refs:
            footer_parts = []
            for ref in draft.source_refs[:3]:
                if ref.page_number:
                    footer_parts.append(f"p.{ref.page_number} {ref.section_title}".strip())
                else:
                    footer_parts.append(ref.section_title or "section")
            footer_text = "Sources: " + " | ".join(footer_parts)
            footer_box = slide.shapes.add_textbox(Inches(0.9), Inches(6.75), Inches(11.2), Inches(0.3))
            footer_tf = footer_box.text_frame
            fp = footer_tf.paragraphs[0]
            fp.text = footer_text
            fp.font.size = Pt(theme.footer_font_size)
            fp.font.color.rgb = RGBColor(100, 116, 139)

    def _attach_notes(self, slide, notes: str) -> None:
        try:
            notes_text_frame = slide.notes_slide.notes_text_frame
            notes_text_frame.text = notes
        except Exception:
            # python-pptx notes support can be inconsistent across versions.
            pass
